<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-D3HDG58" name="Test 2" tests="2" failures="2" timestamp="28 Apr 2020 10:49:09 GMT" time="18.123" errors="0">
  <testcase name="contactUs" time="18.015" classname="com.testng.classes.ContactUsTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.testng.classes.ContactUsTest.contactUs(ContactUsTest.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- contactUs -->
  <testcase name="contactUs" time="18.02" classname="com.testng.classes.ContactUsTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ExtentReporter.ReporterClass.getScreenshot(ReporterClass.java:39)
	at com.ExtentReporter.Listener.onTestFailure(Listener.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- contactUs -->
</testsuite> <!-- Test 2 -->
